version: "3.8"

services:
  dev-environment:
    build: .
    container_name: cs3103
    network_mode: "bridge"
    volumes:
      # Mount your code directory for live updates
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    # Keep container running
    command: tail -f /dev/null
